default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: delivery
  username: postgres
  password: 1

test:
  <<: *default
  database: delivery_test
  username: postgres
  password: 1

production:
  adapter: postgresql
  encoding: unicode
  database: urlshortner_production
  username: urlshortner
  password: urlshortner
  host: localhost
  port: 5432
